services:
  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft Mode
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # Allow plaintext (dev mode)
      - ALLOW_PLAINTEXT_LISTENER=yes

      # Memory tuning for 4GB server
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m

    volumes:
      - kafka_data:/bitnami/kafka

    networks:
      - erp-core-net

  mongodb:
    image: mongo:7
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - erp-core-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - erp-core-net

volumes:
  kafka_data:
  mongo_data:

networks:
  erp-core-net:
    external: true