version: "3.8"

services:
  kafka-consumer:
    build: .
    container_name: kafka-consumer
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=notifications
    volumes:
      - /opt/secrets/firebase/firebase-service-account.json:/app/firebase-service-account.json:ro
    networks:
      - shared-backend-net

networks:
  shared-backend-net:
    external: true
