name: Deploy Kafka Infra

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy Kafka infra to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.kafka.yml"
          target: "/opt/kafka-infra"

      - name: Start Kafka stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/kafka-infra
            docker compose -f docker-compose.kafka.yml down
            docker compose -f docker-compose.kafka.yml pull
            docker compose -f docker-compose.kafka.yml up -d
